C3/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path(
        'login', login, name='login'
    ),
    path(
        'register', register, name='register'
    ),
]

C3/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls'))
]

C3/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path(
        '', home, name='home'
    )
]

C3/account/models.py
from django.db import models

# Create your models here.

C3/home/models.py
from django.db import models

# Create your models here.

C3/account/views.py
from django.shortcuts import render

# Create your views here.
def login(req):
    return render(
        req,
        'account/login.html',
        {}
    )

def register(req):
    return render(
        req,
        'account/register.html',{}
    )

C3/home/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.
def home(req):

    data = [
        {
            "title": 'A',
            "subtitle": 'A subtitle',
            "text": '10'
        },
        {
            "title": 'B',
            "subtitle": 'B subtitle',
            "text": '20'
        },
        {
            "title": 'C',
            "subtitle": 'C subtitle',
            "text": '30'
        },
        {
            "title": 'D',
            "subtitle": 'D subtitle',
            "text": '40'
        },
        {
            "title": 'E',
            "subtitle": 'E subtitle',
            "text": '50'
        },
    ]

    return render(
        req,
        'home/index.html',
        {
            'data': data
        }
    )

class Main(View):
    def get(self):
        ...
    def post(self):
        ...

C3/home/templates/home/inc/card.html
{% for d in data %}
    <div class="col-3">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ d.title }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ d.subtitle }}</h6>
            <p class="card-text">{{ d.text }}</p>
          </div>
        </div>
    </div>
{% endfor %}

C3/home/templates/home/index.html
{% extends 'base.html' %}

{% block main %}
    {% include 'home/inc/card.html' %}
{% endblock main %}


{% block header %}
    Home Page
{% endblock header %}


{% block title %}
    Home Page
{% endblock title %}

C3/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

C3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:register' %}">Register</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    DropDown
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Navid</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
              </ul>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>

        <div class="container">

            <div class="row">
                <div class="alert alert-danger">
                    <h1> {% block header %} {% endblock %} </h1>
                </div>
            </div>

            <div class="row my-3 border border-1 p-3">
                {% block main %} {% endblock main %}
            </div>

        </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>